d={}
name = input("Enter Your Name..")
lang = input("Enter Your Language..")
d.update({name:lang})
name = input("Enter Your Name..")
lang = input("Enter Your Language..")
d.update({name:lang})
name = input("Enter Your Name..")
lang = input("Enter Your Language..")
d.update({name:lang})
name = input("Enter Your Name..")
lang = input("Enter Your Language..")
d.update({name:lang})
print(d)
