s =set()
n = int(input("Enter Number 01: "))
s.add(n)
n = int(input("Enter Number 02: "))
s.add(n)
n = int(input("Enter Number 03: "))
s.add(n)
n = int(input("Enter Number 04: "))
s.add(n)
n = int(input("Enter Number 05: "))
s.add(n)
n = int(input("Enter Number 06: "))
s.add(n)
n = int(input("Enter Number 07: "))
s.add(n)
n = (input("Enter Number as string 08: "))
s.add(n)
print(s)
print(len(s))# 06